# Generated by Django 5.2.6 on 2025-10-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('programming', 'Fundamentos de Programação'), ('development', 'Desenvolvimento Web/Mobile'), ('database', 'Banco de Dados'), ('engineering', 'Engenharia de Software'), ('infra', 'Infraestrutura e Redes de Computadores'), ('math', 'Matemática e Lógica Computacional'), ('computing', 'Computação de alto Desempenho')], default='programming', max_length=40),
        ),
    ]
