# Generated by Django 5.2.6 on 2025-10-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='category',
        ),
    ]
