# Generated by Django 5.2.6 on 2025-09-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=100)),
                ('question_body', models.TextField()),
                ('anonymous', models.BooleanField(default=False)),
                ('question_date', models.DateTimeField(auto_now_add=True)),
                ('questions_status', models.BooleanField(default=False)),
            ],
        ),
    ]
